### PR TITLE
Remove vagrant-libvirt from vagrant file

### PR DESCRIPTION
**Pull request by Madhu-1**
Fixes: #21 
Fixes: #20 
Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
tested against `Vagrant 2.0.2` i will test it against newer version

**Comment by Madhu-1** [comment]
@JohnStrunk can you add a do not merge label to this one

**Comment by kshlm** [comment]
`config.vagrant.plugins` is only available in relatively recent versions of vagrant. It works for me on vagrant-2.1.5, but fails in Fedora with vagrant-2.0.2 available from the default repos. Removing this is a good idea.

**Comment by kshlm** [comment]
@Madhu-1 the line only work on vagrant-2.1.x. It works on 2.1.5 without it as well.

**Pull request merged**
